Feat/change get orders
kschltz/lanchonete pull request #11
Opened 2024-01-14 22:10 UTC by Clauber-camilo

Atualizado a query para buscar pedidos. Foi adicionado também uma nova migration para poder fazer inserção de uma nova coluna de pedido chamada `created_at`

2024-01-15 20:26 UTC, kschltz requested changes

2024-01-15 20:26 UTC, kschltz commented on src/mba_fiap/datasource/pedido.clj
> +  (listar
O local da query não deveria ser aqui. Imagina que aqui é uma camada agnostica de acesso aos pedidos. Essa forma específica de listagem é uma regra de negocio, então pode passar ela pra umm UseCase

2024-01-16 00:01 UTC, Clauber-camilo commented on src/mba_fiap/datasource/pedido.clj
> +  (listar
Alterei o lugar da inserção da query customizada

2024-01-16 12:35 UTC, kschltz commented on src/mba_fiap/adapter/pedido_rest.clj
> +        result (pedido.service/listar-pedidos repository (usecase.p/listar-pedidos-abertos))]
nice

2024-01-16 12:36 UTC, kschltz approved these changes

2024-01-16 12:37 UTC, merged