update routes documentation
kschltz/lanchonete pull request #17
Opened 2024-01-27 20:42 UTC by caiocss

2024-01-27 23:53 UTC, kschltz requested changes

2024-01-27 23:53 UTC, kschltz commented on doc/architecture.md
> +### Kubernetes
Eu add uma sessão de  k8s, acho que vale trazer pra cá

2024-01-27 23:53 UTC, kschltz commented on doc/routes.md
> +
mencionar que precisa usar o external IP do minikube como host caso rode via minikube

2024-01-28 20:34 UTC, Clauber-camilo commented on doc/routes.md
> +curl --location 'localhost:8080/pagamento/d7ce1a59-71da-494b-a115-454b1b970c4a'
Nesse ponto funciona a gente passar a rota sem http?

2024-01-28 22:40 UTC, kschltz approved these changes

2024-01-28 22:40 UTC, merged